### ISSUE TITLE
Test business idea with pop up store

### ISSUE THREAD

**Issue by cuminandpaprika** [cuminandpaprika/test-epics#6]
As a business owner, I want to know if people want to buy icecream in the places I want to open a store

- [ ] Organise Cart Rental #7 
- [ ] Purchase ice cream flavors #8 
- [ ] Organise staffing #10 
- [ ] Design logos and branding #10 
- [ ] Marketing for pop up event #11
